//TO display the current location on goolge map(in image)

//the key that is generated by google map api from your account
const GOOGLE_API_KEY = 'AIzaSyAbYnDS2vrAfJArxJPRQPCxnEUOTjMmMhE';

class LocationHelper {
  static String generateLocationPreviewImage(
      {required double? latitude, required double? longitude}) {
    return 'https://maps.googleapis.com/maps/api/staticmap?center=&$latitude,$longitude&zoom=13&size=600x300&maptype=roadmap&markers=color:blue%7Clabel:S%7C$latitude,$longitude&key=$GOOGLE_API_KEY';
  }
}
